"""
Cascavel MITRE ATT&CK Navigator Layer Exporter
Generates a JSON layer that can be imported directly into the MITRE ATT&CK Navigator.
"""

import json
from datetime import datetime
from typing import Any


def generate_mitre_layer(scan_results: dict[str, Any], target: str) -> str:
    """Converts Cascavel scan results into a MITRE ATT&CK Navigator JSON layer."""

    vulns = scan_results.get("vulns", [])
    now = datetime.now().strftime("%Y-%m-%d")

    layer = {
        "name": f"Cascavel Pentest - {target}",
        "versions": {"attack": "14", "navigator": "5.0.0", "layer": "4.5"},
        "domain": "enterprise-attack",
        "description": f"Automated mapping generated by Cascavel v3.0.0 on {now}.",
        "filters": {
            "platforms": ["Windows", "Linux", "macOS", "Network", "Containers"]
        },
        "sorting": 0,
        "layout": {
            "layout": "side",
            "aggregateFunction": "average",
            "showID": False,
            "showName": True,
            "showAggregateScores": False,
            "countUnscored": False,
        },
        "hideDisabled": False,
        "techniques": [],
        "gradient": {
            "colors": [
                "#00D4FF",  # Low/Info
                "#FFC107",  # Medium
                "#FD7E14",  # High
                "#DC3545",  # Critical
            ],
            "minValue": 1,
            "maxValue": 10,
        },
    }

    # Map findings to techniques. (Assuming plugins add 'mitre_id' to findings in the future).
    # For now we provide a sample mechanism based on CWE/OWASP mapping if needed,
    # but the schema expects a 'mitre_id' field.

    technique_dict = {}

    for v in vulns:
        mitre_ids = v.get("mitre_ids", [])
        if not mitre_ids:
            # Fallback heuristic (Example only)
            if "SQL" in v.get("title", ""):
                mitre_ids = ["T1190"]  # Exploit Public-Facing Application

        cvss = float(v.get("cvss_score", 1.0))
        # Prevent 0 score from breaking gradient visualization, set min to 1
        score = max(1.0, cvss)

        for tid in mitre_ids:
            if tid not in technique_dict:
                technique_dict[tid] = {
                    "techniqueID": tid,
                    "score": score,
                    "color": "",
                    "comment": v.get("title", ""),
                    "enabled": True,
                    "metadata": [],
                }
            else:
                # Keep highest score
                if score > technique_dict[tid]["score"]:
                    technique_dict[tid]["score"] = score
                    technique_dict[tid]["comment"] += f" | {v.get('title', '')}"

    layer["techniques"] = list(technique_dict.values())

    return json.dumps(layer, indent=2)


if __name__ == "__main__":
    sample = {
        "vulns": [
            {
                "title": "SQL Injection in Login",
                "cvss_score": 9.8,
                "mitre_ids": ["T1190", "T1566"],
            }
        ]
    }
    print(generate_mitre_layer(sample, "rettecnologia.org"))
