# SPDX-License-Identifier: MIT
# OpenSSF Scorecard — Security health metrics for this repository
# https://securityscorecards.dev
name: OpenSSF Scorecard

on:
  push:
    branches: [main]
  schedule:
    # Runs every Monday at 06:00 UTC
    - cron: "0 6 * * 1"

permissions: read-all

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write  # Upload SARIF
      id-token: write         # Publish results
      actions: read
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - name: Run Scorecard
        uses: ossf/scorecard-action@0864cf19026789058feabb7e87baa5f140aac736 # v2.3.1
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@2e230e8fe0ad3a14a340fac8a0a5526c12d146af # v3
        with:
          sarif_file: results.sarif
